### ISSUE TITLE
Edge paths

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/Superficial#12]
* This is needed even before starting #9.
* It is best to allow degenerate geodesics.
* This will mean having an initial vertex and a vector/list as fields for defining, with a `require` statement verifying that this is a path, and deducing terminal vertex.
* May also want to check that it is in a given 2-complex.

**Comment by Chinmaya-Kausik** [comment]
What all is left under this issue?

**Comment by siddhartha-gadgil** [comment]
Nothing.
