### ISSUE TITLE
Length 0 arc is plotted incorrectly

### ISSUE THREAD

**Issue by shabarishch** [siddhartha-gadgil/Superficial#92]
In the following path,
`val path1 = PLPath(
  NormalPath(
    Vector(
      NormalArc(
        7,
        5,
        SkewPantsHexagon(
          1,
          true,
          Set(
            SkewCurve(PantsBoundary(1, Z3(2)), PantsBoundary(2, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(2, Z3(2)), PantsBoundary(3, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(1, Z3(1)), PantsBoundary(2, Z3(1)), 0.2, 2),
            SkewCurve(PantsBoundary(0, Z3(2)), PantsBoundary(1, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(3, Z3(1)), PantsBoundary(3, Z3(2)), 0.2, 1),
            SkewCurve(PantsBoundary(0, Z3(0)), PantsBoundary(0, Z3(1)), 0.2, 1)
          )
        )
      ),
      NormalArc(
        5,
        3,
        SkewPantsHexagon(
          1,
          false,
          Set(
            SkewCurve(PantsBoundary(1, Z3(2)), PantsBoundary(2, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(2, Z3(2)), PantsBoundary(3, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(1, Z3(1)), PantsBoundary(2, Z3(1)), 0.2, 2),
            SkewCurve(PantsBoundary(0, Z3(2)), PantsBoundary(1, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(3, Z3(1)), PantsBoundary(3, Z3(2)), 0.2, 1),
            SkewCurve(PantsBoundary(0, Z3(0)), PantsBoundary(0, Z3(1)), 0.2, 1)
          )
        )
      ),
      NormalArc(
        0,
        1,
        SkewPantsHexagon(
          2,
          true,
          Set(
            SkewCurve(PantsBoundary(1, Z3(2)), PantsBoundary(2, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(2, Z3(2)), PantsBoundary(3, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(1, Z3(1)), PantsBoundary(2, Z3(1)), 0.2, 2),
            SkewCurve(PantsBoundary(0, Z3(2)), PantsBoundary(1, Z3(0)), 0.2, 1),
            SkewCurve(PantsBoundary(3, Z3(1)), PantsBoundary(3, Z3(2)), 0.2, 1),
            SkewCurve(PantsBoundary(0, Z3(0)), PantsBoundary(0, Z3(1)), 0.2, 1)
          )
        )
      )
    )
  ),
  Vector(0.0, 0.07541963176135802, 0.2),
  Vector(2.15, 0.0, 0.2)
)`
the third arc has zero length. However, while plotting the arc in blue, we get three arcs of non zero length -  
![fig4](https://user-images.githubusercontent.com/78301708/123046750-1c104a80-d41a-11eb-90d3-f8c1d4964389.png)
the first is across edges 20 and 21, the second is nearly parallel to edge 2, and the third runs halfway along edge 14, to continue nowhere. The third arc should just be a point, so that the path starts at a vertex of edge 21 and comes back to it.

**Comment by shabarishch** [comment]
The plotting is correct. I had mistaken finaldisplacement for position. The third arc does not have zero length and it is plotted correctly.

**Comment by siddhartha-gadgil** [comment]
Excellent. I have just finished something I was deeply in for 4 weeks, so I
can think about Superficial again (perhaps today or tomorrow morning).
