### ISSUE TITLE
Checking correctness of systoles

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/Superficial#94]
This is a summary as of June 30, 2021, commit 8a4d9309ed1.

# Non-normal homotopy/isotopy

The subtle part of the code, which needs careful verification, is _homotopies_ of normal curves that change the underlying normal curve. There are two forms of errors:

1. Missed homotopy across vertices.
2. Wrong homotopy across vertices.

## Missed homotopy

* This is the less serious error, as it can be checked post-facto, i.e., after we have computed the systole, to ensure that all the curves are indeed homotopically non-trivial.
* For this, we have to account for all curves in a neighbourhood - these should be part of the systole but recognized as equivalent or be too long.
* We should also check that the underlying normal curves are simple and connected.

## Wrong homotopy

* This can happen anywhere along the way, so we should guard against this.
* The best way seems to be to generate objects that record details of homotopies, and checking later that:
  - these are correct.
  - there is a homotopy starting with every PL curve that is minimal in its normal class which is not part of the systole.
 * One can have a single sealed trait, with the initial curve as a method (and perhaps a `check` function), and with case classes for the different homotopies. 
 * Homotopies as used are stored as side-effects in a buffer to be verified later.
 * Verification of homotopies can be done with:
   - using functions that check validity (implemented separately from creating the homotopy, so easier to check their correctness).
   - plotting the start and end curves and inspecting correctness.
   - the very act of writing the code to generate these will lead to scrutinizing curves where there are homotopies.

@shabarishch Can you check:
- if the summary looks fine and if I am missing something
-  what are the functions where we have a homotopy, and what is the nature of the homotopy (including null-homotopy by returning `None`)

**Comment by shabarishch** [comment]
- Yes, the summary looks all right.
- We look at homotopies only in two functions - `shorten` and `postEnumIsotopyCheck`. Both involve moving paths across vertices when the path passes close to the vertex. Checking for null homotopy only happens in `shorten` by checking whether the path is vertex linking. In `postEnumIsotopyCheck` we have already ruled out homotopically trivial normalpaths, so we don't check for null-homotopy.

**Comment by siddhartha-gadgil** [comment]
I meant the functions where the homotopy is actually generated, and what kind of homotopy. 

@shabarishch - your code is clean so this is easy to track. It is good that the homotopies all occur in `NormalPath`. Here is my list:

* `removeVertexLinkingSubpaths` which in turn calls `endsGoAround` - this involves 
  - deleting subpaths (which are closed and null-homotopic) 
  - recongnising vertex linking closed paths and noting that they are null-homotopic.
* `makeClosedPathsTaut` which involves:
  - removing arcs that begin and end at the same edge.
  - concluding null-homotopy if nothing is left after this.
  - merging pairs of arcs in the same face, which have become adjacent after the removal.
* `vertexLinkingPath`creates a vertex linking path, which we conclude is null-homotopic.
* `otherWayAroundVertex` which uses:
  - splicing a null-homotopic curve (adding it in, the dual of deletion in `removeVertexLinkingClosedPaths`
  - the null-homotopic closed curve is generated by `vertexLinkingPath`

**Comment by shabarishch** [comment]
I think this is complete, except for `uniqueUptoFlipAndCyclicPerm` which chooses a unique representative for a closed NormalPath upto flip and cyclic permutation of arcs.

**Comment by siddhartha-gadgil** [comment]
Thanks. I had missed `uniqueUptoFlipAndCyclicPerm` and as a result the corresponding topological move. As I trace things I am increasingly confident it is correct as it is. But it is still good general practice to separate verification of proofs from generation of proofs, so that verification depends on a smaller amount of code and can be done independently. I will summarize the homotopies used soon.

In the other direction, what we have to verify is that none of the curves in the claimed systole are homotopically trivial, and that no pair of them is close. This can be checked independently. Since curves are simple it suffices to check that either they do not separate or none of the resulting components are discs, which can be verified using Euler characteristics.

**Comment by siddhartha-gadgil** [comment]
@shabarishch I am a bit worried about the `uniqueUptoFlipAndCyclicPerm` function. The criteria that sets are the same works only if the two curves are simple and connected normal curves. Otherwise we will have to argue that they are not part of the systole. But since we may be changing the curve it is a bit messy.

It may be best to modify that function so that it is as stated - we rotate and/or flip and see if curves become the same. Since this is done before enumerating PL Paths it may hurt performance. But I think it is worth it.

A quick way to implement is to map the normal path to the set of curves obtained from it by rotation and flipping, using `splitAt` and `++` to rotate and the flip method for the rest. We can then use `groupBy` with this instead of the `Set` of edges.

What do you think? I can implement on a branch and check performance.

**Comment by shabarishch** [comment]
Yes, that was my first idea but I didn't do it for performance reasons, but we can do it now because we will be having a mechanism to store data. We only need to generate the map `uniqueUptoFlipAndCyclicPerm` once and then store it.

**Comment by siddhartha-gadgil** [comment]
I have made the change. As you say, we can store the map and use it for verification.

**Comment by siddhartha-gadgil** [comment]
So here is my summary of what I think are all the homotopies used. 

## Constructing  Homotopies 

Homotopies are obtained by combining
- specific path homotopies fixing endpoints, including null-homotopies of loops.
- inverses of the specific homotopies.
- homotopy behaviour of *, i.e., from X homotopic to Y, deduce A * X * B homotopic to A * Y * B.
  - cyclic rotations and flipping.

##  Specific homotopies:
1. vertex linking paths are null-homotopic.
2. if there is a single edge E so that the endpoints of all arcs of a closed curve lie on E, then the closed curve is null-homotopic.
3. Given 
   (a) edges E_0, E_1 and E_2 of a fixed face, and
   (b) paths A, B and C in the face with A joining E_1 to E_0, B joining E_2 to E_0 and C joining E_1 to E_2
   (c) collection of arcs P_1, P_2, ..., P_j beginning and ending on E_0
 It follows that the normal path A * P_1*...P_j* B is homotopic fixing endpoints to the path C.

## Empty paths
These will lead to various errors, so we should use `Option[NormalPath[P]]` instead.

@shabarishch please check if all cases are covered.

**Comment by shabarishch** [comment]
I think two small changes are required - 
- The collection of arcs P_1, P_2, ..., P_j can begin and end on E_0 flip as well.
- The path  A * P_1*...P_j* (B^(-1)) is homotopic to C.
Otherwise I think it is complete.

**Comment by siddhartha-gadgil** [comment]
Thanks. I will implement this in the next couple of days, i.e., define homotopy and all methods that change base of a PL path will add a homotopy to a buffer (unless I find a bug in the process).

**Comment by siddhartha-gadgil** [comment]
Allowing normal paths that have succesive edges in the same face (which as @shabarishch pointed out the code does), and assuming all arcs join midpoints (so same edge means equal for the endpoints of a normal arc), it seems that there is a short and clean list of homotopies:
* A normal arc beginning and ending at an edge is null-hommotopic.
* A vertex linking arc is null-homotopic
* If A,B, and C are normal arcs all in a face and `A * B = C` then `A * B` and `C` are null-homotopic.
* An additional _free homotopy_, which does not fix endpoints, is given by cyclic rotation.
* One may also flip, but this should be taken care of by flipping homotopies before composing.

To get all homotopies, one uses relations of loop operations with homotopy, as well as compositions of homotopies.
@shabarishch does this look correct.

**Comment by shabarishch** [comment]
Yes, this looks correct.

**Comment by siddhartha-gadgil** [comment]
* The new method `shortPathsPf` which gives the proofs ran.
* Debugging was needed only in the generation and checking of proofs, giving evidence that the basic code was correct.
* We should add more `ensuring` and `require` in the methods to ensure that the proofs are proving the correct things.

**Comment by siddhartha-gadgil** [comment]
* A new method `shortPathsProved` is non-recursive, wraps `shortPathsPf` ensuring that the proof output is from the specified curve to the final (possibly trivial) _shortest curve.
* This can be replicated fairly fast, loading the enumeration part from data, with the following.

```scala
import superficial._
import PantsSurface._
val surf = PantsSurface.allClosed(2)(1)
val skewsurf = SkewPantsSurface.enumerate(surf, Vector(0.2), Vector(1, 2))(1)
val pathsuptolen5 = NormalPath.enumerate[SkewPantsHexagon](skewsurf, Some(5))
val clpathsuptolen5 = pathsuptolen5.filter(p => p.isClosed)
val uniqclpathsuptolen5 = NormalPath.uniqueUptoFlipAndCyclicPerm(clpathsuptolen5)
val json = os.read(os.pwd/'data/"pllen5.json")
val plpathsuptolen5 = PLPath.minimalClosedFamilyFromJson(json)
val ndgplpaths = plpathsuptolen5.values.flatten.toVector.filter(_.base.length<5)
val shortPathsPf = ndgplpaths.map(path => 
               PLPath.shortenProved(skewsurf, path, 0.05, uniqclpathsuptolen5, plpathsuptolen5))
```
